---
title: "長庚大學 大數據分析方法 作業三"
output: github_document
---
## 網站資料爬取
```{r}
#這是R Code Chunk
##第一次使用要先安裝 install.packages("rvest")

#install.packages("rvest")
library(rvest)

for(i in 1:5){
  PttUrl <- paste0("https://www.ptt.cc/bbs/Tech_Job/index",i,".html")
  PttTechJob <- PttUrl

  PttContent <- read_html(PttTechJob)
  post_title <- PttContent %>% html_nodes(".title") %>% html_text()
  post_pushnum <- PttContent %>% html_nodes(".nrec") %>% html_text()
  post_author <- PttContent %>% html_nodes(".author") %>% html_text()
  
  assign(paste0("PttPosts",i), data.frame(Title = post_title, PushNum = post_pushnum, Author = post_author))
}

  PttPostsAll<-rbind(PttPosts1,PttPosts2,PttPosts3,PttPosts4,PttPosts5)
  tail(PttPostsAll)

##read_html
##html_nodes
##html_text
```

## 爬蟲結果呈現
```{r}
#這是R Code Chunk
knitr::kable(PttPostsAll[1:100,c("Title","PushNum","Author")])

##請將iris取代為上個步驟中產生的爬蟲資料資料框
```

## 解釋爬蟲結果 
```{r}
#這是R Code Chunk
str(PttPostsAll)
```

100 obs.代表有100列，也就是有100篇文章標題。

```{r}
#這是R Code Chunk
table(PttPostsAll$Author)
```

作者longbow2的文章數最多，100篇裡他發了17個文章。

我發現的有趣現象是，裡面有非常多的人詢問和分享面試的心得，但通常這種文章的推文數都很低，反而是一些危言聳聽的標題，例如：[問題] 當找不到工作時，會不會有一種想輕生的 …，或是，Re: [轉錄][就可] 嫁給工程師的好處多?! ^_^，之類的標題就會有很多推文，甚至有「爆」的推文數。
然後發現上面說的longbow2的文章標題都會有個[公告]，原來他是小組長，他正在舉行版主的投票，所以他的文章數特別多。
